package com.fun.entity;

import lombok.Data;

import java.util.Date;

@Data
public class Area {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_area.area_id
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Integer areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_area.area_name
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private String areaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_area.area_desc
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private String areaDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_area.priority
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_area.create_time
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_area.last_edit_time
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Date lastEditTime;


}