package com.fun.entity;

import lombok.Data;

import java.util.Date;

//奖品
@Data
public class Award {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_award.award_id
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Integer awardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_award.award_name
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private String awardName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_award.award_desc
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private String awardDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_award.award_img
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private String awardImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_award.point
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Integer point;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_award.priority
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_award.create_time
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_award.expire_time
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Date expireTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_award.last_edit_time
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Date lastEditTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_award.enable_status
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Integer enableStatus;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_award.shop_id
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Integer shopId;


}