package com.fun.entity;

import lombok.Data;

import java.util.Date;

@Data
public class LocalAuth {
    //用户,个人信息
    private PersonInfo personInfo;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_local_auth.local_auth_id
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Integer localAuthId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_local_auth.user_id
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_local_auth.user_name
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_local_auth.password
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_local_auth.create_time
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_local_auth.last_edit_time
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Date lastEditTime;


}