package com.fun.entity;

import lombok.Data;

import java.util.Date;

@Data
public class PersonInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_person_info.user_id
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Integer userId;

    //1用户2店家3管理员
    private Integer userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_person_info.name
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_person_info.birthday
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_person_info.gender
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_person_info.phone
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_person_info.email
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_person_info.profile_img
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private String profileImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_person_info.customer_flag
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    // private Integer customerFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_person_info.shop_owner_flag
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    //private Integer shopOwnerFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_person_info.admin_flag
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    //private Integer adminFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_person_info.create_time
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_person_info.last_edit_time
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Date lastEditTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_person_info.enable_status
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Integer enableStatus;

}