package com.fun.entity;

import lombok.Data;

@Data
public class PhoneAuth {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_phone_auth.phone_auth_id
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Integer phoneAuthId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_phone_auth.user_id
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_phone_auth.phone
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_phone_auth.auth_number
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private String authNumber;


}