package com.fun.entity;

import lombok.Data;

import java.util.Date;
import java.util.List;

@Data
public class Product {
    private List<ProductImg> productImgList;

    private ProductCategory productCategory;

    private Shop shop;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.product_id
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.product_name
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.product_desc
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private String productDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.img_addr
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private String imgAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.normal_price
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private String normalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.promotion_price
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private String promotionPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.priority
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.create_time
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.last_edit_time
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Date lastEditTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.enable_status
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Integer enableStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.point
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    //积分
    private Integer point;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.product_category_id
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Integer productCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.shop_id
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Integer shopId;


}