package com.fun.entity;

import lombok.Data;

import java.util.Date;

@Data
public class ProductImg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_img.product_img_id
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Integer productImgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_img.img_addr
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private String imgAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_img.img_desc
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private String imgDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_img.priority
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_img.create_time
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_img.product_id
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Integer productId;


}