package com.fun.entity;

import lombok.Data;

import java.util.Date;

@Data
public class ProductCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_category.product_category_id
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Integer productCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_category.product_category_name
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private String productCategoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_category.product_category_desc
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private String productCategoryDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_category.priority
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_category.create_time
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_category.last_edit_time
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Date lastEditTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_category.shop_id
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Integer shopId;


}