package com.fun.entity;

import lombok.Data;

import java.util.Date;

@Data
public class ShopCategory {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_category.shop_category_id
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Integer shopCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_category.shop_category_name
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private String shopCategoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_category.shop_category_desc
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private String shopCategoryDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_category.shop_category_img
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private String shopCategoryImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_category.priority
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_category.create_time
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_category.last_edit_time
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Date lastEditTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_category.parent_id
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Integer parentId;


}