package com.fun.entity;

import lombok.Data;

import java.util.Date;

@Data
public class Shop {
    //区域
    private Area area;
    //商店类别
    private ShopCategory shopCategory;
    //注册用户
    private PersonInfo owner;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.shop_id
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Integer shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.owner_id
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Integer ownerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.area_id
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Integer areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.shop_category_id
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Integer shopCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.parent_category_id
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Integer parentCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.shop_name
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private String shopName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.shop_desc
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private String shopDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.shop_addr
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private String shopAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.phone
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.shop_img
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private String shopImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.longitude
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Double longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.latitude
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Double latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.priority
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.create_time
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.last_edit_time
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Date lastEditTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.enable_status
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Integer enableStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.advice
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private String advice;


}