package com.fun.entity;

import lombok.Data;

import java.util.Date;

/**
 * 顾客已领取奖品映射
 */
@Data
public class UserAwardMap {
    //用户信息
    private PersonInfo user;
    //奖品
    private Award award;
    //员工信息
    private PersonInfo operator;
    //商店
    private Shop shop;

    private Integer operatorId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_award_map.user_award_id
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Integer userAwardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_award_map.user_id
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_award_map.award_id
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Integer awardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_award_map.shop_id
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Integer shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_award_map.user_name
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_award_map.award_name
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private String awardName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_award_map.expire_time
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Date expireTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_award_map.create_time
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_award_map.used_status
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    //O为领取1已领取
    private Integer usedStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_award_map.point
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Integer point;


}