package com.fun.entity;

import lombok.Data;

import java.util.Date;

/**
 * 顾客消费商品的映射
 */
@Data
public class UserProductMap {
    //所属商店
    private Shop shop;
    //消费用户信息
    private PersonInfo user;
    //商品信息
    private Product product;
    //操作的员工信息
    private PersonInfo operator;

    private Integer operatorId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_product_map.user_product_id
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Integer userProductId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_product_map.user_id
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_product_map.product_id
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_product_map.shop_id
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Integer shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_product_map.user_name
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_product_map.product_name
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_product_map.create_time
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_product_map.point
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    //消费商品所获积分
    private Integer point;


}