package com.fun.entity;

import lombok.Data;

import java.util.Date;

@Data
public class WechatAuth {
    //用户信息
    private PersonInfo personInfo;


    //微信获取用户信息的凭证,对公众号有唯一性
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wechat_auth.wechat_auth_id
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Integer wechatAuthId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wechat_auth.user_id
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Integer userId;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wechat_auth.create_time
     *
     * @mbggenerated Sun Nov 25 19:26:11 CST 2018
     */
    private Date createTime;


}